variables = {}

# adding training features for the NMSSM di-Higgs analysis
variables["nmssm"] = [
    "pt_1",
    "pt_2",
    "eta_1",
    "phi_1",
    "eta_2",
    "phi_2",
    "deltaR_ditaupair",
    "m_vis",
    "bpair_pt_1",
    "bpair_eta_1",
    "bpair_phi_1",
    "bpair_pt_2",
    "bpair_eta_2",
    "bpair_phi_2",
    "bpair_m_inv",
    "bpair_deltaR",
    "bpair_pt_dijet",
    "fj_Xbb_pt",
    "fj_Xbb_eta",
    "fj_Xbb_phi",
    "fj_Xbb_msoftdrop",
    "fj_Xbb_nsubjettiness_2over1",
    "met",
    "metphi",
]

variables["nmssm_v2"] = [
    "massX",
    "massY",
    "njets",
    "nbtag",
    "pt_1",
    "pt_2",
    "eta_1",
    "phi_1",
    "eta_2",
    "phi_2",
    "deltaR_ditaupair",
    "m_vis",
    "m_fastmtt",
    "pt_fastmtt",
    "eta_fastmtt",
    "phi_fastmtt",
    "bpair_pt_1",
    "bpair_eta_1",
    "bpair_phi_1",
    "bpair_pt_2",
    "bpair_eta_2",
    "bpair_phi_2",
    "bpair_m_inv",
    "bpair_deltaR",
    "bpair_pt_dijet",
    # "fj_Xbb_pt",
    # "fj_Xbb_eta",
    # "fj_Xbb_phi",
    # "fj_Xbb_msoftdrop",
    # "fj_Xbb_nsubjettiness_2over1",
    "met",
    "metphi",
    "mass_tautaubb",
    "pt_tautaubb",
    "jpt_1",
    "jpt_2",
    "mjj",
]
