variables = {}

# adding training features for the NMSSM di-Higgs resolved analysis
variables["nmssm"] = [
    "njets",
    "nbtag",
    "nfatjets",
    "pt_1",
    "pt_2",
    "eta_1",
    # "phi_1",
    "eta_2",
    # "phi_2",
    "deltaR_ditaupair",
    "m_vis",
    "m_fastmtt",
    "pt_fastmtt",
    "eta_fastmtt",
    # "phi_fastmtt",
    "bpair_pt_1",
    "bpair_eta_1",
    # "bpair_phi_1",
    "bpair_btag_value_1",
    "bpair_pt_2",
    "bpair_eta_2",
    # "bpair_phi_2",
    "bpair_btag_value_2",
    "bpair_m_inv",
    "bpair_deltaR",
    "bpair_pt_dijet",
    "fj_Xbb_pt",
    "fj_Xbb_eta",
    # "fj_Xbb_phi",
    "fj_Xbb_msoftdrop",
    "fj_Xbb_nsubjettiness_2over1",
    # "fj_Xbb_nsubjettiness_3over2", # has NaN values, due to wrong eta cut 
    "met",
    # "metphi",
    "mass_tautaubb",
    "pt_tautaubb",
    "kinfit_mX",
    "kinfit_mY",
    "kinfit_chi2",
    "mt_1",
    # "deltaPhi_met_tau1",
    # "deltaPhi_met_tau2",
    # "jpt_1",
    # "jpt_2",
    # "mjj",
    "massX",
    "massY",
]

# adding training features for the NMSSM di-Higgs boosted analysis
variables["nmssm_boosted"] = [
    "njets_boosted",
    "nbtag_boosted",
    "nfatjets_boosted",
    "boosted_pt_1",
    "boosted_pt_2",
    "boosted_eta_1",
    # "boosted_phi_1",
    "boosted_eta_2",
    # "boosted_phi_2",
    "boosted_deltaR_ditaupair",
    "boosted_m_vis",
    "boosted_m_fastmtt",
    "boosted_pt_fastmtt",
    "boosted_eta_fastmtt",
    # "boosted_phi_fastmtt",
    "bpair_pt_1_boosted",
    "bpair_eta_1_boosted",
    # "bpair_phi_1_boosted",
    "bpair_btag_value_1_boosted",
    "bpair_pt_2_boosted",
    "bpair_eta_2_boosted",
    # "bpair_phi_2_boosted",
    "bpair_btag_value_2_boosted",
    "bpair_m_inv_boosted",
    "bpair_deltaR_boosted",
    "bpair_pt_dijet_boosted",
    "fj_Xbb_pt_boosted",
    "fj_Xbb_eta_boosted",
    # "fj_Xbb_phi_boosted",
    "fj_Xbb_msoftdrop_boosted",
    "fj_Xbb_nsubjettiness_2over1_boosted",
    "met_boosted",
    # "metphi_boosted",
    "boosted_mass_tautaubb",
    "boosted_pt_tautaubb",
    "kinfit_mX_boosted",
    "kinfit_mY_boosted",
    "kinfit_chi2_boosted",
    "boosted_mt_1",
    "massX",
    "massY",
]
